import '../models/product.dart';

const Map<int, String> kProductTitlesVi = {
  1: 'Mascara tạo mi Essence Lash Princess',
  2: 'Bảng phấn mắt 16 ô kèm gương',
  3: 'Phấn phủ dạng hộp tiện dụng',
  4: 'Son môi đỏ quyến rũ',
  5: 'Sơn móng tay màu đỏ',
  6: 'Nước hoa Calvin Klein CK One',
  7: 'Nước hoa Chanel Coco Noir',
  8: 'Nước hoa Dior J\'adore',
  9: 'Nước hoa Dolce Shine',
  10: 'Nước hoa Gucci Bloom',
  11: 'Giường ngủ đôi Annibale Colombo cao cấp',
  12: 'Ghế sofa Annibale Colombo',
  13: 'Tủ đầu giường gỗ anh đào châu Phi',
  14: 'Ghế hội nghị điều hành Knoll Saarinen',
  15: 'Chậu rửa mặt gỗ có gương treo tường',
  16: 'Táo tươi nhập khẩu',
  17: 'Thịt bò bít-tết tươi',
  18: 'Thức ăn cho mèo Cat Food',
  19: 'Thịt gà tươi sạch',
  20: 'Dầu ăn thực vật tinh luyện',
  21: 'Dưa chuột tươi',
  22: 'Thức ăn cho chó Pedigree',
  23: 'Trứng gà tươi sạch',
  24: 'Cá phi lê tươi',
  25: 'Ớt chuông xanh tươi',
  26: 'Ớt xanh tươi',
  27: 'Mật ong rừng nguyên chất',
  28: 'Kem que mát lạnh',
  29: 'Nước ép trái cây tươi',
  30: 'Kiwi tươi nhập khẩu',
  31: 'Chanh tươi',
  32: 'Sữa tươi tiệt trùng',
  33: 'Dâu tằm tươi',
  34: 'Cà phê Nescafé hòa tan',
  35: 'Khoai tây tươi',
  36: 'Bột Protein thể hình',
  37: 'Hành tây đỏ tươi',
  38: 'Gạo trắng hạt dài',
  39: 'Nước ngọt có ga',
  40: 'Dâu tây tươi',
  41: 'Hộp khăn giấy tiện dụng',
  42: 'Nước uống tinh khiết',
  43: 'Xích đu trang trí phòng khách',
  44: 'Khung ảnh cây gia đình',
  45: 'Cây trang trí để nhà',
  46: 'Chậu cây xanh trang trí',
  47: 'Đèn bàn trang trí nội thất',
  48: 'Thìa xới cơm gỗ tre tự nhiên',
  49: 'Cốc nhôm cao cấp màu đen',
  50: 'Dụng cụ đánh trứng màu đen',
  51: 'Máy xay sinh tố để bàn',
  52: 'Chảo thép carbon chịu nhiệt',
  53: 'Thớt cắt thực phẩm đa năng',
  54: 'Dụng cụ vắt cam chanh màu vàng',
  55: 'Dụng cụ thái trứng tiện dụng',
  56: 'Bếp điện gia đình đa năng',
  57: 'Rây lọc mịn nhuyễn',
  58: 'Nĩa dùng bữa đa năng',
  59: 'Ly thủy tinh cao cấp',
  60: 'Dụng cụ bào thực phẩm màu đen',
  61: 'Máy xay cầm tay đa tốc độ',
  62: 'Khay làm đá viên',
  63: 'Rây bếp đa năng',
  64: 'Dao bếp cao cấp chống gỉ',
  65: 'Hộp cơm giữ nhiệt tiện lợi',
  66: 'Lò vi sóng gia đình đa năng',
  67: 'Giá treo cốc gỗ',
  68: 'Chảo chiên chống dính',
  69: 'Đĩa ăn sứ cao cấp',
  70: 'Kẹp gắp thực phẩm màu đỏ',
  71: 'Nồi inox nắp kính trong suốt',
  72: 'Xẻng lật thức ăn',
  73: 'Kệ đựng gia vị bếp',
  74: 'Muỗng/Thìa ăn',
  75: 'Khay phục vụ đa năng',
  76: 'Cây cán bột gỗ',
  77: 'Dụng cụ gọt vỏ màu vàng',
  78: 'Laptop Apple MacBook Pro 14 inch',
  79: 'Laptop Asus Zenbook Pro hai màn hình',
  80: 'Laptop Huawei Matebook X Pro',
  81: 'Laptop Lenovo Yoga 920 dạng gập',
  82: 'Laptop Dell XPS 13 mỏng nhẹ cao cấp',
  83: 'Áo sơ mi nam kẻ xanh đen',
  84: 'Áo thun nam Gigabyte Aorus gaming',
  85: 'Áo sơ mi nam kẻ caro',
  86: 'Áo sơ mi nam tay ngắn',
  87: 'Áo sơ mi nam kẻ ô vuông',
  88: 'Giày Nike Air Jordan 1 đỏ đen',
  89: 'Giày bóng chày Nike nam',
  90: 'Giày thể thao Puma Future Rider',
  91: 'Giày sneaker trắng đỏ thời trang',
  92: 'Giày sneaker thể thao trắng đỏ',
  93: 'Đồng hồ nam dây da nâu',
  94: 'Đồng hồ cơ Longines Master Collection',
  95: 'Đồng hồ Rolex Cellini mặt đen',
  96: 'Đồng hồ Rolex Cellini Moonphase',
  97: 'Đồng hồ Rolex Datejust cao cấp',
  98: 'Đồng hồ lặn Rolex Submariner',
  99: 'Loa thông minh Amazon Echo Plus',
  100: 'Tai nghe không dây Apple AirPods',
  101: 'Tai nghe chụp tai Apple AirPods Max',
  102: 'Sạc không dây Apple Airpower',
  103: 'Loa thông minh Apple HomePod Mini',
  104: 'Cáp sạc iPhone chính hãng',
  105: 'Pin dự phòng không dây Apple MagSafe',
  106: 'Đồng hồ Apple Watch Series 4 vàng',
  107: 'Tai nghe không dây Beats Flex',
  108: 'Ốp lưng silicone iPhone 12 màu tím',
  109: 'Gậy chụp ảnh Monopod',
  110: 'Đèn selfie kẹp điện thoại',
  111: 'Gậy selfie đa năng',
  112: 'Chân đế camera studio chuyên dụng',
  113: 'Xe máy đa năng tiện dụng',
  114: 'Xe mô tô Kawasaki Z800',
  115: 'Xe mô tô thể thao MotoGP',
  116: 'Xe tay ga tiện dụng',
  117: 'Xe mô tô thể thao',
  118: 'Xà phòng rửa tay Attitude Super Leaves',
  119: 'Sữa tắm dưỡng ẩm Olay Shea Butter',
  120: 'Kem dưỡng thể và mặt Vaseline Men',
  121: 'Điện thoại iPhone 5s',
  122: 'Điện thoại iPhone 6',
  123: 'Điện thoại iPhone 13 Pro',
  124: 'Điện thoại iPhone X',
  125: 'Điện thoại Oppo A57',
  126: 'Điện thoại Oppo F19 Pro Plus',
  127: 'Điện thoại Oppo K1',
  128: 'Điện thoại Realme C35',
  129: 'Điện thoại Realme X',
  130: 'Điện thoại Realme XT',
  131: 'Điện thoại Samsung Galaxy S7',
  132: 'Điện thoại Samsung Galaxy S8',
  133: 'Điện thoại Samsung Galaxy S10',
  134: 'Điện thoại Vivo S1',
  135: 'Điện thoại Vivo V9',
  136: 'Điện thoại Vivo X21',
  137: 'Bóng bầu dục Mỹ',
  138: 'Bóng chày',
  139: 'Găng tay bóng chày',
  140: 'Bóng rổ cao cấp',
  141: 'Vành rổ bóng rổ',
  142: 'Bóng cricket',
  143: 'Gậy đánh bóng cricket',
  144: 'Mũ bảo hiểm cricket',
  145: 'Khung cổng cricket',
  146: 'Cầu lông vũ',
  147: 'Bóng đá chính hãng',
  148: 'Bóng golf',
  149: 'Gậy golf sắt',
  150: 'Gậy bóng chày kim loại',
  151: 'Bóng tennis',
  152: 'Vợt tennis cao cấp',
  153: 'Bóng chuyền cao cấp',
  154: 'Kính mát đen phong cách',
  155: 'Kính mát cổ điển thời trang',
  156: 'Kính mát xanh đen nổi bật',
  157: 'Kính mát dự tiệc',
  158: 'Kính mát phong cách đường phố',
  159: 'Máy tính bảng iPad Mini 2021',
  160: 'Máy tính bảng Samsung Galaxy Tab S8 Plus',
  161: 'Máy tính bảng Samsung Galaxy Tab trắng',
  162: 'Đầm tay ngắn màu xanh',
  163: 'Đầm mùa hè nữ',
  164: 'Đầm màu xám thời trang',
  165: 'Đầm ngắn dễ thương',
  166: 'Đầm kẻ caro thời trang',
  167: 'Xe Chrysler 300 Touring',
  168: 'Xe Dodge Charger SXT',
  169: 'Xe SUV Dodge Hornet GT Plus',
  170: 'Xe SUV Dodge Durango SXT',
  171: 'Xe MPV Chrysler Pacifica Touring',
  172: 'Túi xách nữ màu xanh da trời',
  173: 'Túi da nữ Heshe cao cấp',
  174: 'Túi xách nữ Prada',
  175: 'Balo nữ da PU màu trắng',
  176: 'Túi xách nữ màu đen thanh lịch',
  177: 'Đầm dạ hội nữ màu đen',
  178: 'Áo corset da kèm chân váy',
  179: 'Áo corset kèm chân váy đen',
  180: 'Đầm nữ họa tiết hạt đậu',
  181: 'Bộ vest đỏ đen Marni',
  182: 'Khuyên tai đá pha lê xanh',
  183: 'Bông tai elip xanh thời trang',
  184: 'Bông tai chủ đề nhiệt đới',
  185: 'Dép nữ đen nâu thoải mái',
  186: 'Giày cao gót Calvin Klein',
  187: 'Giày nữ màu vàng thời trang',
  188: 'Giày nữ Pampi phong cách',
  189: 'Giày nữ màu đỏ quyến rũ',
  190: 'Đồng hồ nữ IWC Ingenieur tự động thép',
  191: 'Đồng hồ nữ Rolex Cellini Moonphase',
  192: 'Đồng hồ nữ Rolex Datejust',
  193: 'Đồng hồ nữ mạ vàng sang trọng',
  194: 'Đồng hồ đeo tay nữ thời trang',
};

const Map<String, String> kCategoryLabelsVi = {
  'beauty': 'Mỹ phẩm',
  'fragrances': 'Nước hoa',
  'furniture': 'Nội thất',
  'groceries': 'Tạp hóa',
  'home-decoration': 'Trang trí nhà',
  'kitchen-accessories': 'Phụ kiện bếp',
  'laptops': 'Laptop',
  'mens-shirts': 'Áo nam',
  'mens-shoes': 'Giày nam',
  'mens-watches': 'Đồng hồ nam',
  'mobile-accessories': 'Phụ kiện mobile',
  'motorcycle': 'Xe máy',
  'skin-care': 'Chăm sóc da',
  'smartphones': 'Điện thoại',
  'sports-accessories': 'Phụ kiện thể thao',
  'sunglasses': 'Kính mát',
  'tablets': 'Máy tính bảng',
  'tops': 'Áo nữ',
  'vehicle': 'Xe cộ',
  'womens-bags': 'Túi nữ',
  'womens-dresses': 'Đầm nữ',
  'womens-jewellery': 'Trang sức nữ',
  'womens-shoes': 'Giày nữ',
  'womens-watches': 'Đồng hồ nữ',
};

String localizedCategoryLabel(String category) {
  final key = category.toLowerCase().trim();
  return kCategoryLabelsVi[key] ?? _titleCase(category.replaceAll('-', ' '));
}

String localizedProductTitle(Product product) {
  return kProductTitlesVi[product.id] ?? product.title;
}

String localizedProductSearchText(Product product) {
  return [
    localizedProductTitle(product),
    localizedCategoryLabel(product.category),
    product.title,
  ].join(' ').toLowerCase();
}

String _titleCase(String value) {
  return value
      .split(' ')
      .map((word) {
        if (word.isEmpty) return word;
        return '${word[0].toUpperCase()}${word.substring(1)}';
      })
      .join(' ');
}
